'use client';
import { useState } from 'react';
import { AlertTriangle, CheckCircle2, ClipboardCheck, Loader2, SearchCheck, ShieldAlert } from 'lucide-react';
import './formative-quality.css';

type Review={overallVerdict:'양호'|'수정 권장'|'검토 필요';summary:string;distribution:{recall:number;understanding:number;application:number};coverageNotes:string[];items:Array<{number:number;verdict:'통과'|'수정 권장'|'검토 필요';testedObjective:string;flags:Array<{category:string;severity:'낮음'|'중간'|'높음';message:string;suggestion:string}>}>};
export function FormativeQualityStudio(){
 const [questions,setQuestions]=useState('');const [objectives,setObjectives]=useState('');const [taughtScope,setTaughtScope]=useState('');const [loading,setLoading]=useState(false);const [error,setError]=useState('');const [review,setReview]=useState<Review|null>(null);
 async function analyze(){if(questions.trim().length<20)return;setLoading(true);setError('');setReview(null);try{const response=await fetch('/api/professor/quality/analyze',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({questions,objectives,taughtScope})});const payload=await response.json();if(!response.ok||!payload.ok)throw new Error(payload?.error?.message??'품질 검사를 완료하지 못했습니다.');setReview(payload.data)}catch(cause){setError(cause instanceof Error?cause.message:'품질 검사를 완료하지 못했습니다.')}finally{setLoading(false)}}
 const issueCount=review?.items.reduce((sum,item)=>sum+item.flags.length,0)??0;
 return <div className="quality-studio"><header className="quality-heading"><div><p>형성평가 품질 검사</p><h1>좋은 질문인지,<br/>배포 전에 확인하세요.</h1><span>정답을 다시 만드는 대신 학생의 학습을 방해할 수 있는 문항 위험을 찾아냅니다.</span></div><div className="quality-boundary"><ShieldAlert size={19}/><div><b>형성평가 우선</b><small>최종 판단은 교수에게 있습니다</small></div></div></header><div className="quality-layout"><main><section className="quality-input"><div className="quality-section-head"><h2>검토할 문항</h2><span>문항 번호와 선택지를 함께 붙여넣기</span></div><textarea value={questions} onChange={e=>setQuestions(e.target.value)} placeholder={'1. 다음 중 옳은 것은?\n① ...\n② ...\n정답: ②'} /></section><section className="quality-context"><div className="quality-section-head"><h2>판정 기준</h2><span>선택 입력 · 정확도가 높아집니다</span></div><label><span>학습목표</span><textarea value={objectives} onChange={e=>setObjectives(e.target.value)} placeholder="예: 항부정맥제의 작용기전을 설명할 수 있다."/></label><label><span>수업에서 다룬 범위</span><textarea value={taughtScope} onChange={e=>setTaughtScope(e.target.value)} placeholder="강의 목차나 핵심 내용을 붙여넣으세요."/></label></section>{error&&<div className="quality-error" role="alert"><AlertTriangle size={17}/>{error}</div>}{review&&<section className="quality-results"><div className="quality-summary"><div><span className={`quality-verdict is-${review.overallVerdict.replace(' ','-')}`}>{review.overallVerdict}</span><h2>검사 결과</h2><p>{review.summary}</p></div><dl><div><dt>문항</dt><dd>{review.items.length}</dd></div><div><dt>발견 항목</dt><dd>{issueCount}</dd></div></dl></div><div className="quality-distribution"><h3>인지 수준 분포</h3><div><span>회상 <b>{review.distribution.recall}</b></span><span>이해 <b>{review.distribution.understanding}</b></span><span>적용 <b>{review.distribution.application}</b></span></div>{review.coverageNotes.map(note=><p key={note}><SearchCheck size={15}/>{note}</p>)}</div><div className="quality-ledger">{review.items.map(item=><article key={item.number}><div className="quality-item-no"><span>{item.number}</span><small>{item.verdict}</small></div><div><h3>{item.testedObjective}</h3>{item.flags.length===0?<p className="quality-pass"><CheckCircle2 size={16}/>뚜렷한 위험 신호를 찾지 못했습니다.</p>:item.flags.map((flag,index)=><div className="quality-flag" key={`${flag.category}-${index}`}><header><b>{flag.category}</b><span>{flag.severity}</span></header><p>{flag.message}</p><small><b>수정 제안</b>{flag.suggestion}</small></div>)}</div></article>)}</div></section>}</main><aside className="quality-run"><ClipboardCheck size={20}/><h2>검사 범위</h2><ul><li>복수정답 가능성</li><li>모호한 표현</li><li>정답 단서</li><li>수업 범위·목표 정렬</li><li>인지 수준 편중</li></ul><button type="button" disabled={questions.trim().length<20||loading} onClick={analyze}>{loading?<><Loader2 className="quality-spin" size={17}/> 검사 중</>:<>문항 품질 검사</>}</button><p>AI 결과는 교수 검토용 의견이며 자동 승인이나 학생 공개로 이어지지 않습니다.</p></aside></div></div>
}
