'use client';
import {useCallback,useEffect,useMemo,useRef,useState} from 'react';
import {BookOpen,Download,Expand,Link2,Play,Square,UserX} from 'lucide-react';
import {QRCodeCanvas} from 'qrcode.react';
import {createBrowserClient} from '@/lib/db/browser';
import './live-assessment.css';
import './live-assessment-progress.css';
export function LiveProfessorDashboard({sessionId}:{sessionId:string}){
 const[data,setData]=useState<any>(),[error,setError]=useState('');const qr=useRef<HTMLCanvasElement>(null);
 const load=useCallback(()=>fetch(`/api/professor/live-sessions/${sessionId}`).then(r=>r.json()).then(p=>p.ok?setData(p.data):setError(p.error?.message)),[sessionId]);
 useEffect(()=>{load();const db=createBrowserClient();const channel=db.channel(`live-${sessionId}`).on('postgres_changes',{event:'*',schema:'public',table:'live_assessment_participants',filter:`session_id=eq.${sessionId}`},load).on('postgres_changes',{event:'*',schema:'public',table:'live_assessment_answers'},load).subscribe();const timer=setInterval(load,5000);return()=>{clearInterval(timer);db.removeChannel(channel)}},[load,sessionId]);
 const url=typeof window==='undefined'?'':`${location.origin}/join?code=${data?.session.join_code??''}`,questions=data?.session.question_snapshot??[],participants=data?.participants??[],submitted=participants.filter((p:any)=>p.status==='submitted').length;
 const stats=useMemo(()=>questions.map((q:any)=>{const responses=participants.flatMap((p:any)=>p.live_assessment_answers??[]).filter((a:any)=>a.item_id===q.id);return{...q,count:responses.length,correct:responses.filter((a:any)=>a.selected_index===q.answerIndex).length,choiceCounts:q.choices.map((_:any,i:number)=>responses.filter((a:any)=>a.selected_index===i).length)}}),[questions,participants]);
 async function action(next:'start'|'end'){if(next==='end'&&!confirm(`아직 제출하지 않은 학생은 ${participants.length-submitted}명입니다. 미응답은 오답 처리하고 종료할까요?`))return;await fetch(`/api/professor/live-sessions/${sessionId}`,{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({action:next,confirm:true})});load()}
 if(!data)return <main className="live-shell">{error||'평가실을 준비하고 있습니다.'}</main>;const s=data.session;
 return <main className="live-shell"><header className="live-head"><div><p>실시간 형성평가 · {s.status==='lobby'?'대기':s.status==='live'?'진행 중':'종료'}</p><h1>{s.title}</h1></div>{s.status==='lobby'?<button onClick={()=>action('start')}><Play/> 평가 시작</button>:s.status==='live'?<button className="danger" onClick={()=>action('end')}><Square/> 평가 종료</button>:null}</header>
 {s.status==='lobby'&&<section className="lobby-grid"><div className="qr-card"><QRCodeCanvas ref={qr} value={url} size={270} level="M"/><b>{s.join_code}</b><div><button onClick={()=>navigator.clipboard.writeText(url)}><Link2/>링크 복사</button><button onClick={()=>{const link=document.createElement('a');link.download=`${s.join_code}-qr.png`;link.href=qr.current!.toDataURL();link.click()}}><Download/>QR 저장</button><button onClick={()=>document.documentElement.requestFullscreen()}><Expand/>전체 화면</button></div></div><div className="people-card"><h2>입장 학생 <b>{participants.length}</b></h2>{participants.map((p:any)=><div key={p.id}><span>{p.name}</span><small>{new Date(p.joined_at).toLocaleTimeString()}</small><button aria-label="내보내기" onClick={async()=>{await fetch(`/api/professor/live-sessions/${sessionId}?participantId=${p.id}`,{method:'DELETE'});load()}}><UserX/></button></div>)}</div></section>}
 {s.status==='live'&&<section className="live-progress-card"><div className="live-progress-illustration"><BookOpen/><i/><i/><i/></div><p>형성평가가 진행 중입니다</p><h2>{submitted}/{participants.length} 제출 완료</h2><span>의대 학습의 시작과 복습을 LectureLink에서 함께하세요.</span></section>}
 {s.status==='ended'&&<><section className="metric-row"><div><small>전체 참여</small><b>{participants.length}</b></div><div><small>제출 완료</small><b>{submitted}</b></div><div><small>평균 점수</small><b>{participants.length?Math.round(participants.reduce((n:number,p:any)=>n+(p.score??0),0)/participants.length):'—'}</b></div></section><section className="analysis-card"><h2>문항별 응답 현황</h2>{stats.map((q:any,i:number)=><article key={q.id}><div><b>{i+1}. {q.stem}</b><span>{q.count}/{participants.length} 응답 · 정답률 {q.count?Math.round(q.correct/q.count*100):0}%</span></div><div className="bar-row">{q.choices.map((c:string,n:number)=><span key={c} style={{flex:q.choiceCounts[n]+1}}>{n+1}번 {q.choiceCounts[n]}</span>)}</div></article>)}</section><section className="analysis-card"><h2>학생별 결과</h2>{[...participants].sort((a:any,b:any)=>(b.score??0)-(a.score??0)).map((p:any)=><div className="result-line" key={p.id}><span>{p.name}{p.auto_submitted?' · 자동 제출':''}</span><b>{p.score}/{p.total}</b></div>)}</section></>}</main>
}
