'use client';
import { useEffect, useRef, useState } from 'react';
import Link from 'next/link';
import { useSearchParams } from 'next/navigation';
import { AlertTriangle, CheckCircle2, FileText, Loader2, Presentation, ShieldCheck, Upload, X } from 'lucide-react';
import './material-improvement.css';

type SlideReview={slide:number;title:string;density:'낮음'|'적정'|'높음';issues:string[];recommendation:string;safeActions:string[]};
type Review={deckTitle:string;summary:string;overallScore:number;strengths:string[];priorityActions:string[];slides:SlideReview[];artifactId:string};
export function MaterialImprovementStudio(){
 const searchParams=useSearchParams();
 const inputRef=useRef<HTMLInputElement>(null); const [file,setFile]=useState<File|null>(null); const [goal,setGoal]=useState('가독성 개선'); const [audience,setAudience]=useState('의과대학 학생'); const [preserve,setPreserve]=useState(true); const [loading,setLoading]=useState(false); const [error,setError]=useState(''); const [review,setReview]=useState<Review|null>(null);
 const[courses,setCourses]=useState<Array<{id:string;title:string}>>([]);const[courseId,setCourseId]=useState(searchParams.get('course')??'');
 useEffect(()=>{fetch('/api/professor/courses').then(r=>r.json()).then(p=>p.ok&&setCourses(p.data))},[]);
 async function analyze(){if(!file||!courseId)return;setLoading(true);setError('');const form=new FormData();form.append('file',file);form.append('courseId',courseId);form.append('goal',goal);form.append('audience',audience);form.append('preserve',String(preserve));try{const response=await fetch('/api/professor/materials/analyze',{method:'POST',body:form});const payload=await response.json();if(!response.ok||!payload.ok)throw new Error(payload?.error?.message??'분석하지 못했습니다.');setReview(payload.data)}catch(cause){setError(cause instanceof Error?cause.message:'분석하지 못했습니다.')}finally{setLoading(false)}}
 return <div className="material-studio">
  <header className="material-heading"><div><p>강의자료 개선</p><h1>내용은 그대로,<br/>읽히는 순서는 더 분명하게.</h1><span>원본 PPTX의 텍스트 구조를 분석해 교수 검토용 개선안을 만듭니다.</span></div><div className="material-safety"><ShieldCheck size={18}/><div><b>원본 보존 모드</b><small>파일을 직접 수정하지 않습니다</small></div></div></header>
  <div className="material-layout"><main>
   <section className="material-panel"><div className="material-panel-head"><h2>분석할 강의자료</h2><span>1개 파일 · 최대 25MB</span></div>{!file?<button type="button" className="material-upload" onClick={()=>inputRef.current?.click()}><Upload size={22}/><span><b>PPTX 선택</b><small>도형과 이미지가 아닌 텍스트 구조부터 진단합니다</small></span></button>:<div className="material-selected"><Presentation size={22}/><span><b>{file.name}</b><small>{(file.size/1024/1024).toFixed(1)} MB</small></span><button type="button" aria-label="파일 제거" onClick={()=>{setFile(null);setReview(null)}}><X size={17}/></button></div>}<input hidden ref={inputRef} type="file" accept=".pptx,application/vnd.openxmlformats-officedocument.presentationml.presentation" onChange={e=>{setFile(e.target.files?.[0]??null);setReview(null)}}/></section>
   <section className="material-panel"><div className="material-panel-head"><h2>개선 기준</h2><span>프롬프트 없이 선택</span></div><div className="material-controls"><label><span>우선 목표</span><select value={goal} onChange={e=>setGoal(e.target.value)}><option>가독성 개선</option><option>핵심 내용 강조</option><option>긴 슬라이드 분할</option><option>수업 흐름 정리</option></select></label><label><span>대상</span><select value={audience} onChange={e=>setAudience(e.target.value)}><option>의과대학 학생</option><option>전공의</option><option>보건의료계열 학생</option></select></label><label className="material-check"><input type="checkbox" checked={preserve} onChange={e=>setPreserve(e.target.checked)}/><span><b>의학 내용 보존</b><small>새로운 의학 지식을 임의로 추가하지 않습니다.</small></span></label></div></section>
   {error&&<div className="material-error" role="alert"><AlertTriangle size={17}/>{error}</div>}
   {review&&<section className="material-results"><div className="material-score"><span>{review.overallScore}</span><div><small>가독성 진단</small><h2>{review.deckTitle}</h2><p>{review.summary}</p></div></div><div className="material-priorities"><div><h3>잘 된 점</h3>{review.strengths.map(item=><p key={item}><CheckCircle2 size={15}/>{item}</p>)}</div><div><h3>먼저 고칠 부분</h3>{review.priorityActions.map(item=><p key={item}><AlertTriangle size={15}/>{item}</p>)}</div></div><div className="slide-review-list">{review.slides.map(slide=><article key={slide.slide}><div className="slide-review-no"><span>{slide.slide}</span><small>{slide.density} 밀도</small></div><div><h3>{slide.title}</h3>{slide.issues.length>0&&<ul>{slide.issues.map(issue=><li key={issue}>{issue}</li>)}</ul>}<p className="slide-recommendation"><b>개선안</b>{slide.recommendation}</p><div className="safe-actions">{slide.safeActions.map(action=><span key={action}>{action}</span>)}</div></div></article>)}</div></section>}
  </main><aside className="material-run"><FileText size={19}/><h2>분석 범위</h2><dl><div><dt>저장할 차시</dt><dd><select value={courseId} onChange={e=>setCourseId(e.target.value)}><option value="">차시 선택</option>{courses.map(c=><option key={c.id} value={c.id}>{c.title}</option>)}</select></dd></div><div><dt>파일</dt><dd>{file?.name??'선택 전'}</dd></div><div><dt>목표</dt><dd>{goal}</dd></div><div><dt>대상</dt><dd>{audience}</dd></div><div><dt>내용 보존</dt><dd>{preserve?'켜짐':'꺼짐'}</dd></div></dl><button type="button" disabled={!file||!courseId||loading} onClick={analyze}>{loading?<><Loader2 className="material-spin" size={17}/> 분석 중</>:<>진단하고 차시에 저장</>}</button>{review?.artifactId&&<Link className="workspace-return" href={`/professor/courses/${courseId}`}>저장됨 · 차시로 돌아가기</Link>}<p>결과는 선택한 차시에 자동 저장되며 원본 PPTX는 변경하지 않습니다.</p></aside></div>
 </div>
}
